print("Welcome to madlib!")
print("What's your name?")
name = input()
print("Nice to meet you, " + name + ".")
print("Please type a noun.")
noun1 = input()
print("Now a verb with -ing.")
verb1 = input()
print("And then an adjective.")
adjective = input()
print("Name a place.")
place = input()
print("Please type a random name.")
given_name = input()
print("Now type another verb with -ing.")
verb2 = input()
print("Now we need another noun.")
noun2 = input()
print("One more noun.")
noun3 = input()
print("Type a place and then we can get started!")
place2 = input()
#This is where the story starts------------------------------
print("One day " + name + " was hanging out at " + place2 + ".")
print(place2 + " had been particularly " + adjective + " that day.")
print(name + " had gotten bored and decided to start " + verb1 + ".")
print("The sound of the " + verb1 + " was very loud and annoying to everyone " + verb2 + " nearby.")
print(given_name + " actually liked the sound of the " + verb1 + " and started " + verb1 + " as well.")
print("Everyone noticed all the " + verb1 + " and eventually just started to " + verb1 + " too.")
print("Some people tried " + verb1 + " with a " + noun1 + ".")
print("Others tried with a " + noun2 + ".")
print("Most people were just " + verb1 + " with a " + noun3 + ".")
print("The " + verb1 + " could be heard miles away at " + place + ".")
print("The End!")
